### ISSUE TITLE
Profile shortlinks don't work

### ISSUE THREAD

**Issue by jeremycryan** [JamBrain/JamBrain#2269]
There's an option to copy a shortlink from the user profile page:

![image](https://github.com/JamBrain/JamBrain/assets/22649301/153b22ea-cb63-4136-a2be-a27b4a531975)

As far as I can tell, none of the resulting links work for any users. They're in the format [https://ldj.am/$11](https://ldj.am/$11).

**Comment by jeremycryan** [comment]
They seem to work now --- not sure what was going on in September before LD54.

**Comment by mikekasprzak** [comment]
If I remember correctly ldj.am expired, and though I was quick to remedy
that, dotfm was slow to reactivate it.

I reeeeally wish they would allow .am domain transfers. 😡
